name: Bug Report
description: Report a bug or issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this?
      placeholder: |
        1. Run `shh --style casual`
        2. Press Enter after 5 seconds
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages if any.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Run `shh --version` or `pip show shh-cli`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      description: Run `python --version`
      placeholder: "3.11.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
